[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
PIP_NO_CACHE_DIR = "1"
